// data.js — Static data for HDR Sports

const CATEGORIES = [
  {
    id: 'bats',
    slug: 'bats',
    name: 'Cricket Bats',
    description: 'English willow & Kashmir willow bats for every level of play.',
    productCount: 35,
    emoji: '🏏',
    color: '#8B4513',
  },
  {
    id: 'balls',
    slug: 'balls',
    name: 'Cricket Balls',
    description: 'Premium leather balls — red, white, and pink for all formats.',
    productCount: 20,
    emoji: '⚾',
    color: '#8B0000',
  },
  {
    id: 'gloves',
    slug: 'gloves',
    name: 'Batting Gloves',
    description: 'Superior grip and protection for confident stroke play.',
    productCount: 18,
    emoji: '🥊',
    color: '#2D5A27',
  },
  {
    id: 'wicketkeeping',
    slug: 'wicketkeeping',
    name: 'Wicketkeeping Gear',
    description: 'Gloves and pads engineered for elite keepers.',
    productCount: 12,
    emoji: '🧤',
    color: '#1A3A5C',
  },
  {
    id: 'pads',
    slug: 'pads',
    name: 'Protective Pads',
    description: 'Batting, thigh, arm, chest, and abdominal protection.',
    productCount: 28,
    emoji: '🛡️',
    color: '#4A4A4A',
  },
  {
    id: 'kits',
    slug: 'kits',
    name: 'Full Cricket Kits',
    description: 'Complete team kits with custom branding options.',
    productCount: 10,
    emoji: '🎒',
    color: '#C9A23A',
  },
];

const PRODUCTS = [
  // ─── BATS ───────────────────────────────────────────────
  {
    id: 'bat-001',
    name: 'HDR Elite Pro Bat',
    category: 'bats',
    tag: 'Best Seller',
    tagline: 'Tournament-grade English willow for elite batsmen.',
    description: 'Handcrafted from Grade 1 English willow, the HDR Elite Pro offers a full, even-grained blade with a thick, rounded edge profile. Ideal for aggressive stroke play, OEM branding available with full custom sticker, grip, and toe-guard options.',
    specs: [
      { label: 'Willow Grade', value: 'Grade 1 English Willow' },
      { label: 'Handle', value: 'Oval Sarawak Cane' },
      { label: 'Profile', value: 'Mid-to-High Bow' },
      { label: 'Edge Thickness', value: '38–42mm' },
      { label: 'Weight', value: '1150–1250g' },
      { label: 'Available Sizes', value: 'SH, LH, Harrow, 5, 6' },
    ],
    features: ['Full grains, no blemish', 'Double-pressed blade', 'Anti-scuff sheet included', 'Custom sticker available'],
    moq: 25,
    images: [],
    emoji: '🏏',
  },
  {
    id: 'bat-002',
    name: 'HDR Championship Bat',
    category: 'bats',
    tag: 'New',
    tagline: 'Grade 2 English willow — performance without compromise.',
    description: 'The Championship Bat is built for club-level and academy players who demand professional feel at a competitive price. Grade 2 English willow with natural grains and a medium bow profile.',
    specs: [
      { label: 'Willow Grade', value: 'Grade 2 English Willow' },
      { label: 'Handle', value: 'Round Cane' },
      { label: 'Profile', value: 'Medium Bow' },
      { label: 'Edge Thickness', value: '35–38mm' },
      { label: 'Weight', value: '1100–1200g' },
      { label: 'Available Sizes', value: 'SH, LH, Harrow' },
    ],
    features: ['6–10 natural grains', 'Pre-knocked', 'Custom grip available', 'Sticker customization'],
    moq: 25,
    images: [],
    emoji: '🏏',
  },
  {
    id: 'bat-003',
    name: 'HDR Kashmir Pro Bat',
    category: 'bats',
    tag: null,
    tagline: 'Premium Kashmir willow for training and entry-level play.',
    description: 'Manufactured from top-grade Kashmir willow, this bat offers excellent durability and playability for training sessions, school programs, and entry-level club cricket. Perfect for bulk OEM orders.',
    specs: [
      { label: 'Willow Grade', value: 'Grade A Kashmir Willow' },
      { label: 'Handle', value: 'Cane' },
      { label: 'Profile', value: 'Low-to-Mid Bow' },
      { label: 'Weight', value: '1050–1150g' },
      { label: 'Available Sizes', value: 'SH, LH, Harrow, 4, 5, 6' },
    ],
    features: ['High density wood', 'Durable toe', 'Bulk pricing available', 'School/academy suitable'],
    moq: 50,
    images: [],
    emoji: '🏏',
  },

  // ─── BALLS ───────────────────────────────────────────────
  {
    id: 'ball-001',
    name: 'HDR Test Match Ball',
    category: 'balls',
    tag: 'Best Seller',
    tagline: 'Hand-stitched red leather — built for Test cricket standards.',
    description: 'Our flagship red cricket ball is hand-stitched with alum-tanned English leather. Pronounced seam, consistent weight distribution, and durable lacquer finish make it the choice of club and professional teams globally.',
    specs: [
      { label: 'Leather', value: 'Alum-Tanned English Leather' },
      { label: 'Stitching', value: 'Hand-stitched, 6-row seam' },
      { label: 'Weight', value: '155.9–163g' },
      { label: 'Circumference', value: '224–229mm' },
      { label: 'Certification', value: 'ICC Standard' },
      { label: 'Color', value: 'Red / White / Pink' },
    ],
    features: ['Hand-stitched seam', 'Consistent lacquer', 'ICC standard weight', 'Available in red, white, pink'],
    moq: 100,
    images: [],
    emoji: '🔴',
  },
  {
    id: 'ball-002',
    name: 'HDR White T20 Ball',
    category: 'balls',
    tag: 'New',
    tagline: 'High-visibility white leather for limited-overs cricket.',
    description: 'Designed for T20 and ODI formats, the HDR White T20 Ball features superior seam visibility under floodlights and a durable white finish that maintains condition through 20 overs.',
    specs: [
      { label: 'Leather', value: 'Premium Cowhide' },
      { label: 'Stitching', value: 'Machine + hand finish' },
      { label: 'Weight', value: '155.9–163g' },
      { label: 'Color', value: 'White' },
    ],
    features: ['Floodlight visibility', 'Durable white lacquer', 'Consistent swing', 'Soft core option'],
    moq: 100,
    images: [],
    emoji: '⚪',
  },

  // ─── GLOVES ───────────────────────────────────────────────
  {
    id: 'glove-001',
    name: 'HDR Pro Batting Gloves',
    category: 'gloves',
    tag: 'Best Seller',
    tagline: 'Superior grip, ventilation, and impact protection.',
    description: 'The HDR Pro Batting Gloves combine a full-grain leather palm with high-density foam finger protection. Designed for maximum grip without sacrificing feel, these gloves are standard issue for professional squads and available in custom team colors.',
    specs: [
      { label: 'Palm Material', value: 'Full-Grain Calf Leather' },
      { label: 'Finger Protection', value: 'Dual-density PU foam' },
      { label: 'Back Material', value: 'Mesh + Lycra' },
      { label: 'Sizes', value: 'S, M, L, XL, Youth' },
      { label: 'Hand', value: 'Right & Left hand' },
    ],
    features: ['Perforated palm', 'Wrist strap closure', 'Machine washable', 'Custom color/logo'],
    moq: 30,
    images: [],
    emoji: '🥊',
  },
  {
    id: 'glove-002',
    name: 'HDR Club Batting Gloves',
    category: 'gloves',
    tag: null,
    tagline: 'Durable training gloves for club and academy use.',
    description: 'Built tough for daily training, the HDR Club Gloves offer reliable protection and grip at an accessible price point. Ideal for bulk orders for academies, schools, and club programs.',
    specs: [
      { label: 'Palm Material', value: 'PU Leather' },
      { label: 'Protection', value: 'HD foam padding' },
      { label: 'Sizes', value: 'S, M, L, XL, Youth' },
    ],
    features: ['Reinforced seams', 'Velcro wrist strap', 'Affordable bulk pricing'],
    moq: 50,
    images: [],
    emoji: '🥊',
  },

  // ─── WICKETKEEPING ───────────────────────────────────────
  {
    id: 'wk-001',
    name: 'HDR Pro Keeping Gloves',
    category: 'wicketkeeping',
    tag: 'Best Seller',
    tagline: 'Elite wicketkeeping gloves for professional keepers.',
    description: 'Designed in consultation with international wicketkeepers, the HDR Pro Keeping Gloves offer a snug anatomical fit, premium inner glove, and external rubber inners for sharp catching. Custom branding on fingers and cuff available.',
    specs: [
      { label: 'Outer Palm', value: 'Premium Pimple Rubber' },
      { label: 'Inner Glove', value: 'Chamois leather' },
      { label: 'Wrist Support', value: 'Elasticated cuff' },
      { label: 'Sizes', value: 'S, M, L, XL' },
    ],
    features: ['Anatomical fit', 'Chamois inner', 'Rubber inners for grip', 'Custom embroidery'],
    moq: 25,
    images: [],
    emoji: '🧤',
  },
  {
    id: 'wk-002',
    name: 'HDR Keeping Pads',
    category: 'wicketkeeping',
    tag: null,
    tagline: 'Lightweight keeping pads for agile footwork.',
    description: 'The HDR Keeping Pads are designed to be low-profile and lightweight, allowing keepers to move freely without sacrificing protection. Available in white and custom team colors.',
    specs: [
      { label: 'Material', value: 'PU outer, HD foam inner' },
      { label: 'Height', value: '37–40cm (adjustable)' },
      { label: 'Straps', value: '3-strap velcro' },
      { label: 'Weight', value: '600g per pad' },
    ],
    features: ['Low-profile design', '3-strap velcro', 'Custom color', 'Durable buckles'],
    moq: 30,
    images: [],
    emoji: '🛡️',
  },

  // ─── PADS ───────────────────────────────────────────────
  {
    id: 'pad-001',
    name: 'HDR Elite Batting Pads',
    category: 'pads',
    tag: 'Best Seller',
    tagline: 'Pro-level batting pads with maximum knee roll protection.',
    description: 'The HDR Elite Batting Pads feature a triple-bolster knee roll, extended shin protection, and a streamlined lightweight chassis. Professional grade — used by international players. Full custom color, logo, and name available for team orders.',
    specs: [
      { label: 'Outer Material', value: 'PU Leather' },
      { label: 'Inner Filling', value: 'Multi-density foam' },
      { label: 'Knee Roll', value: 'Triple bolster' },
      { label: 'Straps', value: '3-strap velcro + ankle' },
      { label: 'Sizes', value: 'Adult, Intermediate, Youth' },
      { label: 'Leg', value: 'Right & Left hand' },
    ],
    features: ['Lightweight chassis', 'Ergonomic knee roll', 'Custom color/branding', 'Low-bounce shell'],
    moq: 25,
    images: [],
    emoji: '🛡️',
  },
  {
    id: 'pad-002',
    name: 'HDR Thigh Guard',
    category: 'pads',
    tag: null,
    tagline: 'Contoured thigh protection for right and left-hand batsmen.',
    description: 'Ergonomically shaped to fit the natural contour of the thigh, the HDR Thigh Guard is made from high-density impact foam with a comfortable PU outer shell. Available in inner and outer thigh versions.',
    specs: [
      { label: 'Material', value: 'HD impact foam + PU shell' },
      { label: 'Attachment', value: 'Velcro strap to trousers' },
      { label: 'Type', value: 'Inner & Outer thigh' },
      { label: 'Sizes', value: 'S, M, L, XL' },
    ],
    features: ['Contoured fit', 'Lightweight', 'Custom color', 'Velcro attachment'],
    moq: 50,
    images: [],
    emoji: '🛡️',
  },
  {
    id: 'pad-003',
    name: 'HDR Arm Guard',
    category: 'pads',
    tag: null,
    tagline: 'Full forearm protection without restricting movement.',
    description: 'Constructed from a hard ABS shell backed by high-density foam, the HDR Arm Guard protects the forearm from impact while allowing full range of motion. Elastic strap system for secure fit.',
    specs: [
      { label: 'Shell', value: 'ABS hard shell' },
      { label: 'Padding', value: 'HD foam' },
      { label: 'Attachment', value: 'Dual elastic strap' },
      { label: 'Sizes', value: 'Adult, Youth' },
    ],
    features: ['Hard ABS shell', 'Full forearm coverage', 'Lightweight', 'Custom logos'],
    moq: 50,
    images: [],
    emoji: '💪',
  },
  {
    id: 'pad-004',
    name: 'HDR Chest Guard',
    category: 'pads',
    tag: null,
    tagline: 'Anatomical chest protection for pace conditions.',
    description: 'The HDR Chest Guard is shaped to the torso with a dual-layer HD foam construction and ABS hard plates on the most exposed zones. Breathable mesh back panel with adjustable harness.',
    specs: [
      { label: 'Shell', value: 'ABS hard plate' },
      { label: 'Inner', value: 'Dual-layer HD foam' },
      { label: 'Back', value: 'Breathable mesh harness' },
      { label: 'Sizes', value: 'Adult, Youth' },
    ],
    features: ['Anatomical shaping', 'Dual-layer foam', 'Adjustable harness', 'Custom coloring'],
    moq: 25,
    images: [],
    emoji: '🦺',
  },

  // ─── KITS ───────────────────────────────────────────────
  {
    id: 'kit-001',
    name: 'HDR Team Kit — Full Set',
    category: 'kits',
    tag: 'Best Seller',
    tagline: 'Complete custom-branded cricket kit for your entire team.',
    description: 'The HDR Full Team Kit includes bats, batting gloves, pads, helmet, kit bag, and practice balls — all with your team branding. Perfect for clubs, academies, and national associations. Bulk pricing available from 11 sets.',
    specs: [
      { label: 'Bat', value: 'Grade A Kashmir Willow' },
      { label: 'Gloves', value: 'PU leather batting gloves' },
      { label: 'Pads', value: 'HD foam batting pads' },
      { label: 'Helmet', value: 'ABS shell + steel grill' },
      { label: 'Bag', value: 'Wheeled kit bag with logo' },
      { label: 'Ball', value: '6x match balls' },
    ],
    features: ['All-in-one solution', 'Custom team logo on all items', 'Bulk pricing from 11 sets', 'Matching kit bag'],
    moq: 11,
    images: [],
    emoji: '🎒',
  },
  {
    id: 'kit-002',
    name: 'HDR Academy Starter Kit',
    category: 'kits',
    tag: 'New',
    tagline: 'Everything a young cricketer needs to start playing.',
    description: 'Tailored for junior players and academies, the HDR Academy Starter Kit includes a Kashmir willow bat in junior sizes, youth batting gloves, youth pads, and a kit bag. Custom academy branding available.',
    specs: [
      { label: 'Bat', value: 'Kashmir Willow — Sizes 4,5,6,Harrow' },
      { label: 'Gloves', value: 'Youth batting gloves' },
      { label: 'Pads', value: 'Youth batting pads' },
      { label: 'Bag', value: 'Nylon kit bag' },
    ],
    features: ['Junior-specific sizing', 'Academy branding', 'Affordable bulk price', 'Complete package'],
    moq: 15,
    images: [],
    emoji: '🎒',
  },
];
